[workspace]

members = [ 
    "aquatic_cli_helpers",
    "aquatic_common",
    "aquatic_udp",
    "aquatic_udp_bench",
    "aquatic_udp_load_test",
    "aquatic_udp_protocol",
    "aquatic_ws",
    "plot_pareto"
]

[profile.release]
debug = true
lto = "thin" # Using thin LTO when doing PGO removes build errors
