[package]
name = "aquatic_udp"
version = "0.1.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Blazingly fast, multi-threaded UDP BitTorrent tracker"
repository = "https://github.com/greatest-ape/aquatic"

[lib]
name = "aquatic_udp"
path = "src/lib/lib.rs"

[[bin]]
name = "aquatic_udp"

[features]
io_uring = ["rio", "async-executor", "futures-lite"]

[dependencies]
anyhow = "1"
async-executor = { version = "1", optional = true }
aquatic_cli_helpers = "0.1.0"
aquatic_common = "0.1.0"
aquatic_udp_protocol = "0.1.0"
crossbeam-channel = "0.5"
futures-lite = { version = "1", optional = true }
hashbrown = "0.11.2"
histogram = "0.6"
indexmap = "1"
log = "0.4"
mimalloc = { version = "0.1", default-features = false }
mio = { version = "0.7", features = ["udp", "os-poll", "os-util"] }
parking_lot = "0.11"
privdrop = "0.5"
rand = { version = "0.8", features = ["small_rng"] }
rio = { version = "0.9", optional = true }
serde = { version = "1", features = ["derive"] }
socket2 = { version = "0.4.1", features = ["all"] }

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"
