[package]
name = "aquatic_udp_protocol"
description = "UDP BitTorrent tracker protocol"
keywords = ["udp", "protocol", "peer-to-peer", "torrent", "bittorrent"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true

[features]
serde = ["dep:serde", "dep:serde_with"]

[dependencies]
aquatic_peer_id.workspace = true

byteorder = "1"
cfg-if = "1"
either = "1"
zerocopy = { version = "0.7", features = ["derive"] }

# serde feature
serde = { version = "1", optional = true }
serde_with = { version = "3", features = ["hex"], optional = true }

[dev-dependencies]
pretty_assertions = "1"
serde_json = "1"
quickcheck = "1"
quickcheck_macros = "1"
